var searchList = [];

for(var i=0;i<30;i++){
    searchList.push({
        type:Math.random()<0.5?'scene':'application',
        sceneOrApplications:{
            "applicationId": 10000+i,
            "deleteBy": null,
            "deleteDt": null,
            "updateBy": null,
            "updateDt": "2018-03-15 20:44:21",
            "createBy": 1,
            "createDt": "2018-03-12 17:49:02",
            "orderNum": 18,
            "attendNum": 9,
            "remark": "这里是应用培训的描述",
            "applicationUrl": "http://192.168.3.191:8091/gqsp",
            "type": 10005,
            "name": "应用培训",
            "image1": null,
            "image2": null,
            "image3": null,
            "image4": null,
            "image5": null,
            "newTag": 1,
            "hotTag": null,
            "pinyin": "yingyongpeixun",
            "startNum": null,
            "endNum": null,
            "typeValue": "服务中心",
            "userRating": 5.0,
            "isAttend": 0,
            "isInteresting": 1,
            "userId": null,
            "ifPublish": 1,
            "isDelete": null,
            "deptId": 1,
            "userDeptId": null,
            "isDefault": 0,
            "icon": "http://192.168.3.97:8081/hbtxjw/resource/images/icon/yingyongpeixun.png",
            "recommend": [
                {
                    "applicationId": 10025,
                    "deleteBy": null,
                    "deleteDt": null,
                    "updateBy": null,
                    "updateDt": "2018-03-15 20:56:27",
                    "createBy": 1,
                    "createDt": "2018-03-12 17:49:00",
                    "orderNum": 4,
                    "attendNum": 80,
                    "remark": "这里是人脸识别应用的描述",
                    "applicationUrl": "http://192.168.3.191:8091/gqsp",
                    "type": 10001,
                    "name": "人脸识别应用",
                    "image1": null,
                    "image2": null,
                    "image3": null,
                    "image4": null,
                    "image5": null,
                    "newTag": null,
                    "hotTag": 1,
                    "pinyin": "renlianshibieyingyong",
                    "startNum": null,
                    "endNum": null,
                    "typeValue": null,
                    "userRating": 5.0,
                    "isAttend": null,
                    "isInteresting": null,
                    "userId": null,
                    "ifPublish": 1,
                    "isDelete": null,
                    "deptId": 1,
                    "userDeptId": null,
                    "isDefault": null,
                    "icon": "http://192.168.3.97:8081/hbtxjw/resource/images/icon/renlianshibie.png",
                    "recommend": null,
                    "clickNum": 326
                },
                {
                    "applicationId": 10023,
                    "deleteBy": null,
                    "deleteDt": null,
                    "updateBy": null,
                    "updateDt": "2018-03-15 20:53:18",
                    "createBy": 1,
                    "createDt": "2018-03-12 17:49:00",
                    "orderNum": 2,
                    "attendNum": 89,
                    "remark": "这里是智侦的描述",
                    "applicationUrl": "http://192.168.3.191:8091/gqsp",
                    "type": 10001,
                    "name": "智侦",
                    "image1": null,
                    "image2": null,
                    "image3": null,
                    "image4": null,
                    "image5": null,
                    "newTag": null,
                    "hotTag": 1,
                    "pinyin": "zhizhen",
                    "startNum": null,
                    "endNum": null,
                    "typeValue": null,
                    "userRating": 5.0,
                    "isAttend": null,
                    "isInteresting": null,
                    "userId": null,
                    "ifPublish": 1,
                    "isDelete": null,
                    "deptId": 1,
                    "userDeptId": null,
                    "isDefault": null,
                    "icon": "http://192.168.3.97:8081/hbtxjw/resource/images/icon/zhizhen.png",
                    "recommend": null,
                    "clickNum": 632
                }
            ],
            "clickNum": 963+i
        },
    })
}
var testData = {
    result:"success",
    total:30,
    searchList:searchList,
    searchValue:'编程语言实现模式'
};
console.log(testData);
var t = JSON.stringify(testData)
fs.writeFileSync('./searchList.json',t)